# Try to follow the same order as presented in https://alacritty.org/config-alacritty.html
#
# When configuring a new machine do
# ln -s ~/.config/dotfiles/shell/alacritty.toml ~/.config/alacritty/alacritty.toml

[window]

padding = { x = 11, y = 1 }

option_as_alt = "OnlyRight"


[font]

normal.family = "Anonymous Pro"

size = 16


[cursor]

style = { blinking = "Always" }


[terminal]

shell = { program = "/opt/homebrew/bin/bash", args = ["-l"] }


[keyboard]

bindings = [
 { key = "N", mods = "Command", action = "SpawnNewInstance" },
 { key = "Return", mods = "Shift", chars = "\u001B\r" }
]
