#!/bin/bash
# -*- mode: shell-script -*-

# Alias definitions.

## Use `exa` instead of `ls` if available.
if [[ $(command -v exa) ]]; then
  alias ls='exa'
  alias ll='exa -l'
  alias la='exa -a'
  alias lla='exa -la'
else
  alias ls='ls -G --color=auto'
  alias ll='ls -l'
  alias la='ls -A'
  alias lla='la -l'
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias xterm='xterm -r'

# Add an "alert" alias for long running commands.  Use like so:
#   .alert sleep 15
.alert(){
    start=$(date +%s)
    "$@"
    [ $(($(date +%s) - start)) -le 15 ] || notify-send "Notification" "Long\
 running command \"$(echo $@)\" took $(($(date +%s) - start)) seconds to finish"
}

# jrnl.sh shortcuts
alias .jrnltodo='jrnl @todo -not @done'
alias .jrnltodolist='jrnl @todo-list -on today'

# emacs related
alias .emacs='emacs -l ~/.config/emacs/load-config.el'

# MacOS workaround
if [[ $(uname -n) == "puffin.lan" ]]; then
  alias emacs-org='emacs -g 60x24 --find-file ~/Dropbox/Documents/Orgzly/Anotations.org'
  alias emacs-vanilla='emacs --no-init-file'
fi

# git related
alias .git_checkout_main_pull='git checkout main && git pull'
alias .git_checkout_master_pull='git checkout master && git pull'
alias .git_delete_done_branches='git branch | grep "  done-" | xargs -I {} git branch -d {};'
alias .git_fetch_rebase_origin_development='git fetch origin development:development && git rebase origin/development'
alias .git_fetch_rebase_origin_main='git fetch origin main:main && git rebase origin/main'
alias .git_fetch_rebase_origin_master='git fetch origin master:master && git rebase origin/master'
alias .git_hard_reset_main='git fetch origin main:main && git checkout main && git reset --hard origin/main'
alias .git_hard_reset_master='git fetch origin master:master && git checkout master && git reset --hard origin/master'

alias .date='date --rfc-email --utc'

alias .onefetch='onefetch --no-title --no-color-palette --number-of-authors 5 --number-of-file-churns 5'
