#!/bin/bash
# -*- mode: shell-script -*-

# Alias definitions.

## Use `eza` instead of `ls` if available.
if [[ $(command -v eza) ]]; then
  alias ls='eza'
  alias ll='eza -l'
  alias la='eza -a'
  alias lla='eza -la'
else
  alias ls='ls -G --color=auto'
  alias ll='ls -l'
  alias la='ls -A'
  alias lla='la -l'
fi

## `bat` is a `cat` alternative.
if [[ $(command -v cat) ]]; then
  alias .batcat='bat'
fi

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias xterm='xterm -r'

# Add an "alert" alias for long running commands.  Use like so:
#   .alert sleep 15
.alert(){
    start=$(date +%s)
    "$@"
    [ $(($(date +%s) - start)) -le 15 ] || notify-send "Notification" "Long\
 running command \"$(echo $@)\" took $(($(date +%s) - start)) seconds to finish"
}

# jrnl.sh shortcuts
alias .jrnltodo='jrnl @todo -not @done'
alias .jrnltodolist='jrnl @todo-list -on today'

# emacs related
alias .emacs='emacs -l ~/.config/dotemacs/init.el'

# MacOS workaround
if [[ $(uname -n) == "puffin.lan" ]]; then
  alias emacs-org='emacs -g 60x24 --find-file ~/Dropbox/Documents/Orgzly/Anotations.org'
  alias emacs-vanilla='emacs --no-init-file'
fi

# git related
alias .git_fetch_rebase_origin_master='git fetch origin master:master && git rebase origin/master'
alias .git_hard_reset_master='git fetch origin master:master && git checkout master && git reset --hard origin/master'

alias .date='date --rfc-email --utc'

alias .onefetch='onefetch --no-title --no-color-palette --number-of-authors 5 --number-of-file-churns 5'
