
# The prompt character
[character]
success_symbol = "[Î»êžŠ](bold green)"

[cmd_duration]
format = "[$duration]($style)" # Omit the "took".
min_time = 5_000 # milliseconds

[directory]
truncate_to_repo = false # Show the full path

[elixir]
format = '[$symbol($version \(OTP $otp_version\))]($style) '
symbol = "ðŸ”® "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = ""

[git_status]
format = "[$all_status$ahead_behind]($style) "

[nodejs]
format = "[$symbol($version)]($style) "

[package]
disabled = true # Don't show the package version in repository directories.

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
format = "[$symbol($version)]($style) "
