# -*- mode: shell-script -*-
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

. ~/.dotfiles/shell/alias
. ~/.dotfiles/shell/functions/zsh

# Suggested by Exercism
export PATH=$HOME/Applications:$PATH

# Exercism CLI completion
if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  . ~/.config/exercism/exercism_completion.zsh
fi

# Because of Homebrew
if [[ $(uname) == "Darwin" ]] && [[ -d /usr/local/bin ]]; then
  export PATH="/usr/local/bin:$PATH"
fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# ASDF
if [ -f /usr/local/opt/asdf/asdf.sh ]; then
  . /usr/local/opt/asdf/asdf.sh
  export PATH="$HOME/.asdf/shims:$PATH" 
fi

export PATH="$HOME/.poetry/bin:$PATH"

