# -*- mode: shell-script -*-
#

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# # Source Prezto.
# if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
#   source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
# fi


# Source ZIM.
if [[ -d "${ZIM_HOME}" ]]; then
  source ~/.dotfiles/shell/zim_pre_configuration.zsh
  PURE_PROMPT_SYMBOL='%Bλ≈%b'
fi


# Customize to your needs...

. ~/.dotfiles/shell/alias
. ~/.dotfiles/shell/functions/zsh

# Suggested by Exercism
# export PATH=$HOME/Applications:$PATH

# Exercism CLI completion
if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  . ~/.config/exercism/exercism_completion.zsh
fi

# Because of Homebrew
if [[ $(uname) == "Darwin" ]] && [[ -d /usr/local/bin ]]; then
  export PATH="/usr/local/bin:$PATH"
fi

# ASDF
if [ -f /usr/local/opt/asdf/asdf.sh ]; then
  . /usr/local/opt/asdf/asdf.sh
  export PATH="$HOME/.asdf/shims:$PATH" 
fi

# Prevent Homebrew from uptating all packages when I install something new!
export HOMEBREW_NO_AUTO_UPDATE=1

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source "/Users/bruno.jacquet/Library/Application Support/creds/nexus"

export PATH="/Users/bruno.jacquet/.local/bin:$PATH"
