#!/bin/bash
# -*- mode: shell-script -*-

# Perform Rubocop validation on files different from master branch.
rudi () {
  file="Gemfile"
  if [[ ! -f "$file" ]]; then
    echo "no no no"
    return -1
  fi
    
  if [[ $(grep -q "rails" Gemfile) ]]; then
    echo "yes!"
    exit 0
  fi
}
